// <auto-generated />
using BigWeb.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BigWeb.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231112163636_AddProductToDatabase")]
    partial class AddProductToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BigWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Боевик"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Ужасы"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Мистика"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Триллер"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Драма"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Комедия"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Фэнтензи"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Фантастика"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Нон-фикшн"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Научпоп"
                        });
                });

            modelBuilder.Entity("BigWeb.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Анжей Сапковский",
                            Description = "«Последнее желание» — сборник рассказов писателя Анджея Сапковского в жанре фэнтези, объединённых общим персонажем — ведьмаком Геральтом из Ривии. Это первое произведение из цикла «Ведьмак» как по хронологии, так и по времени написания.",
                            ISBN = "978-5-17-148071-4",
                            ListPrice = 500.0,
                            Price = 485.0,
                            Price100 = 400.0,
                            Price50 = 450.0,
                            Title = "Ведьмак. Последнее желание"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Анжей Сапковский",
                            Description = "«Cборник рассказов Анджея Сапковского в жанре фэнтези, объединённых общим персонажем — ведьмаком Геральтом из Ривии. Это второе произведение из цикла «Ведьмак» как по хронологии, так и по времени написания. В этой части Геральт впервые встречает Цири и находит своё предназначение.",
                            ISBN = "978-5-17-118208-3",
                            ListPrice = 400.0,
                            Price = 385.0,
                            Price100 = 300.0,
                            Price50 = 350.0,
                            Title = "Ведьмак. Меч предназначения"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Анжей Сапковский",
                            Description = "«Третья книга из цикла «Ведьмак» польского писателя Анджея Сапковского.",
                            ISBN = "978-5-17-118219-9",
                            ListPrice = 400.0,
                            Price = 385.0,
                            Price100 = 300.0,
                            Price50 = 350.0,
                            Title = "Ведьмак. Кровь эльфов"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Анжей Сапковский",
                            Description = "«Четвёртая книга из цикла «Ведьмак» польского писателя Анджея Сапковского",
                            ISBN = "978-5-17-118219-9",
                            ListPrice = 650.0,
                            Price = 625.0,
                            Price100 = 525.0,
                            Price50 = 575.0,
                            Title = "Ведьмак. Час презрения"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
