// <auto-generated />
using BigWeb.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BigWeb.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231118175503_AddImageUrl")]
    partial class AddImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BigWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Боевик"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Ужасы"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Мистика"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Триллер"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Драма"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Комедия"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Фэнтензи"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Фантастика"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Нон-фикшн"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Научпоп"
                        });
                });

            modelBuilder.Entity("BigWeb.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Анжей Сапковский",
                            CategoryId = 7,
                            Description = "«Последнее желание» — сборник рассказов писателя Анджея Сапковского в жанре фэнтези, объединённых общим персонажем — ведьмаком Геральтом из Ривии. Это первое произведение из цикла «Ведьмак» как по хронологии, так и по времени написания.",
                            ISBN = "978-5-17-148071-4",
                            ImageUrl = "https://imgproxy.patephone.com/pr:sharp/s:470/dpr:2/plain/https://cdru.patephone.com/ru-fast/c/products/701/150/036/075/113/188121_resized1242.jpg?cc=1543189188000",
                            ListPrice = 500.0,
                            Price = 485.0,
                            Price100 = 400.0,
                            Price50 = 450.0,
                            Title = "Ведьмак. Последнее желание"
                        });
                });

            modelBuilder.Entity("BigWeb.Models.Product", b =>
                {
                    b.HasOne("BigWeb.Models.Category", "CategoryName")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryName");
                });
#pragma warning restore 612, 618
        }
    }
}
