// <auto-generated />
using BigWebBooksRazor_Temp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BigWebBooksRazor_Temp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BigWebBooksRazor_Temp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Боевик"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Ужасы"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Мистика"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Триллер"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Драма"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Комедия"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Фэнтензи"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Фантастика"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Нон-фикшн"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Научпоп"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
